version: "3"
services: 
    app:
        build: 
            context: .

            dockerfile: Dockerfile.create


        ports: 
            - "8080:8080"
        volumes: 
            - ./project:/home/project
            - /home/project/node_modules
        environment: 
            - CHOKIDAR_USEPOLLING=true