FROM node:15.8.0-alpine3.10
RUN npm config set registry http://registry.npmjs.org
RUN npm install -g @vue/cli@4.5.13

WORKDIR /home/project

COPY ./project/package*.json ./
RUN npm install
COPY ./project .

CMD npm run serve