FROM node:16-buster
RUN npm install -g @vue/cli@4.5.13

WORKDIR /home/project

COPY ./project/package*.json ./
RUN npm install
COPY ./project .


RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /home/project/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]