FROM node:15.8.0-alpine3.10
RUN npm config set registry http://registry.npmjs.org
RUN npm install -g @vue/cli@4.5.13

WORKDIR /home/project
CMD tail -f /dev/null

# then :
# docker-compose exec front  bash
# cd ../
# vue create vue