version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: gpu-py39.Dockerfile
    volumes:
      - ./dataset:/home/dataset
      - ./model:/home/model
      - ./src:/home/src
      - ./.vscode-server:/root/.vscode-server
    ports:
      - "8888:8888"
    env_file:
        - ex-of-secret.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mongo:
        image: mongo:3.6.22-xenial
        env_file:
            - ex-of-secret.env
        ports:
            - 27017:27017
        volumes:
            - mongo_ml_session_volume:/data/db
volumes:
  mongo_ml_session_volume:
