version: "3"
services: 
    front:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports: 
            - "8080:8080"
        volumes: 
            - ./frontend/project:/home/project
            - /home/project/node_modules
        environment: 
            - CHOKIDAR_USEPOLLING=true

    ml-server:
        build:
            context: ./ml-server
            dockerfile: Dockerfile.dev
        env_file: 
            - ex-of-secret.env
        ports:
            - "8000:8000"
        volumes:
            - ./ml-server/src:/home/src
            - ./ml-server--vscode-server:/root/.vscode-server

    mongo:
        image: mongo:3.6.22-xenial
        env_file: 
            - ex-of-secret.env
        ports:
            - 27017:27017
        volumes: 
            - mongo_volume:/data/db
volumes: 
  mongo_volume: