version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.py39
    volumes:
      - ./dataset:/home/dataset
      - ./src:/home/src

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]