version: "3"
services: 
    project:
        build: .
        ports: 
            - "8888:8888"
        volumes: 
            - ./vuepress-src:/home/src/docs
            - ./docs:/home/deploy
            - /home/src/docs/node_modules
         
        environment: 
            - CHOKIDAR_USEPOLLING=true