FROM python:3.9.7-buster
WORKDIR /home/src
COPY ./src /home/src/

RUN pip install "fastapi==0.68.1"
RUN pip install uvicorn[standard]
RUN pip install websockets
RUN pip install "pymongo==3.12.0"
RUN pip install "mypy==0.910"

EXPOSE 8000
EXPOSE 8001
CMD uvicorn --host 0.0.0.0 main:app --forwarded-allow-ips '*' --reload 